require("dotenv").config();

let appConfig = {

    SUCCESS_CODE: 200,
    ERROR_CODE_UNAUTHORIZED: 401,
    ERROR_CODE_BAD_REQUEST: 400,
    ERROR_CODE_FORBIDDEN: 403,
    ERROR_CODE: 422,
    ERROR_CODE_BLOCKED_USER: 450,
    ERROR_CODE_DELETED_USER: 451,
    ERROR_CODE_TOO_MAY_ATTEMPTS: 300,
    ERROR_CODE_INTERNAL_SERVER_ERROR: 500,
    ACTIVE_STATUS: 1,
    INACTIVE_STATUS: 0,
    DELETED_STATUS: 2,

    //auth
    USER_CREATED_SUCCESSFULLY: 'USER_CREATED_SUCCESSFULLY',
    ERROR_WHILE_CREATING_USER: 'ERROR_WHILE_CREATING_USER',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_FOUND: 'USER_FOUND',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
    CURRENT_PASSWORD_DOES_NOT_MATCH: 'CURRENT_PASSWORD_DOEST_NOT_MATCH',
    ERROR_WHILE_SAVING_THE_PASSWORD: 'ERROR_WHILE_SAVING_THE_PASSWORD',
    PASSWORD_SAVED_SUCCESSFULLY: "PASSWORD_SAVED_SUCCESSFULLY",
    ERROR_WHILE_SENDING_MAIL: 'ERROR_WHILE_SENDING_MAIL',
    RESET_PASSWORD_MAIL_SENT_SUCCESSFULLY: 'RESET_PASSWORD_MAIL_SENT_SUCCESSFULLY',
    INVALID_TOKEN: 'INVALID_TOKEN',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG'
};

module.exports = appConfig;
